name: ecowise_planner
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0+11

environment:
  sdk: '>=3.3.4 <4.0.0'

dependencies:
  beamer: ^1.6.1
  cloud_firestore: ^4.17.0
  firebase_auth: ^4.19.2
  firebase_core: ^2.30.0
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.5.1
  url_launcher: ^6.2.6
  uuid: ^4.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  assets:
    - images/
