// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBHzEUUZaOzgOqSzSLfSZuz1_VW9W2KXtg',
    appId: '1:461261331968:web:45ad91e1aa4ad68c8a42e5',
    messagingSenderId: '461261331968',
    projectId: 'ecowise-planner',
    authDomain: 'ecowise-planner.firebaseapp.com',
    storageBucket: 'ecowise-planner.appspot.com',
    measurementId: 'G-VJG20PQHF7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCHeHcne0pyYGv4wUY2tbZwpm1YGvljSPE',
    appId: '1:461261331968:android:6f66dd69c68553108a42e5',
    messagingSenderId: '461261331968',
    projectId: 'ecowise-planner',
    storageBucket: 'ecowise-planner.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC-Idm_1bAWIPNdjd-_gPDs9p9pV08oTdY',
    appId: '1:461261331968:ios:345fc161e00029fa8a42e5',
    messagingSenderId: '461261331968',
    projectId: 'ecowise-planner',
    storageBucket: 'ecowise-planner.appspot.com',
    iosBundleId: 'com.o2tech.ecowisePlanner',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC-Idm_1bAWIPNdjd-_gPDs9p9pV08oTdY',
    appId: '1:461261331968:ios:345fc161e00029fa8a42e5',
    messagingSenderId: '461261331968',
    projectId: 'ecowise-planner',
    storageBucket: 'ecowise-planner.appspot.com',
    iosBundleId: 'com.o2tech.ecowisePlanner',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBHzEUUZaOzgOqSzSLfSZuz1_VW9W2KXtg',
    appId: '1:461261331968:web:035a6b2f2dac02338a42e5',
    messagingSenderId: '461261331968',
    projectId: 'ecowise-planner',
    authDomain: 'ecowise-planner.firebaseapp.com',
    storageBucket: 'ecowise-planner.appspot.com',
    measurementId: 'G-6B5X4V1P1M',
  );
}
